version: "3.8"

services:
  labels:
    glance.name: Cardito
    glance.url: https://cardito.info
  nextjs:
    build:
      context: .
    container_name: cardito-info
    restart: unless-stopped
    ports:
      - "4000:4000"
